### ISSUE TITLE
[BUG] Invalid polygons/closed linestrings when smoothing is enabled

### ISSUE THREAD

**Issue by netthier** [mthh/contour-rs#18]
When smoothing is enabled, `ContourBuilder::contours` and probably `ContourBuilder::isobands` can end up generating invalid (self-intersecting) polygons.
E.g.:
Without smoothing:
![image](https://github.com/mthh/contour-rs/assets/66856670/96ec8e31-b679-448a-a209-541a778e56e4)

With smoothing:
![image](https://github.com/mthh/contour-rs/assets/66856670/c81abbc0-6a5e-4c8b-8977-0d65a628b227)

Overlaid:
![image](https://github.com/mthh/contour-rs/assets/66856670/7add1016-a663-44e7-9fc7-cc4ed531f4a6)

I think that [this is invalid according to geo-types](https://docs.rs/geo-types/latest/geo_types/geometry/struct.Polygon.html#validity), and many other geometry standards don't allow this either.
Specifically,
> The interior of the polygon must be a connected point-set. That is, any two distinct points in the interior must admit a curve between these two that lies in the interior.

And,
> The exterior and interior rings must be valid LinearRings (see [LineString](https://docs.rs/geo-types/latest/geo_types/geometry/line_string/struct.LineString.html)).

> Further, a closed `LineString` must not self-intersect. Note that its validity is not enforced, and operations and predicates are undefined on invalid LineStrings.

@mthh You can find the areas the screenshots are from in the dataset I sent you recently at about `557500, 5932680` in its CRS, contours were generated at elevation -5.

**Comment by mthh** [comment]
I'm a but surprised, are you getting this result with version 0.13? 
I can't find this kind of degeneracy when generating contour polygons with your dataset and the smooth option (and I can't find the one you pointed out, but perhaps I generated the contour using a different threshold from yours).

The spikes that are created without smooth don't normally overflow to make self intersecting polygons but instead give the following result (yellow with smooth option and brown without smooth option):

![contours](https://github.com/mthh/contour-rs/assets/12172162/dab97fdc-47eb-4ff4-8697-af98d1dbd16a)

I used to check results of contour-isobands with some validity tests (https://github.com/mthh/geo-validity-check), maybe the same should be done for this crate.

**Comment by mthh** [comment]
Any idea what the problem is here?

**Comment by mthh** [comment]
The culprit change seems to be https://github.com/mthh/contour-rs/commit/b32d16b03e2b549cbaa1061653bf92baa0db238b.

**Comment by netthier** [comment]
Oof yeah that's definitely a mistake with the `as usize` casts. I must've thought those were some other int type at the time.
It's a bit worrying that seemingly no test caught this though.

**Comment by mthh** [comment]
I've tinkered a bit with the code of this function, notably using f64 for intermediate values.

With something like `(point.x as f64 * 2.0 + point.y as f64 * ((self.dx + 1) * 4) as f64) as usize` it doesn't seem to trigger the bug of #12 neither the bug discussed here. But we could go with another index computation (I've made other positive attempts in this direction, but we might as well stay close to the code it's ported to).

Anyway, feel free to propose a fix you're confident with ;)

> It's a bit worrying that seemingly no test caught this though.

Well, now we have a test case to avoid this kind of regression in the future (if you allow me to take a small piece of your raster to include in the tests? otherwise I'll manually create values to reproduce it).
But yes the case test case are still very simples and are mostly pulled from d3-contour. I have two small datasets in the fixtures folder that could also be used into test cases to catch future regressions.

**Comment by netthier** [comment]
That solution makes sense, maybe https://github.com/mthh/contour-rs/issues/17 could be an opportunity to explore alternative ways later :thinking: 
Might also make sense to yank 0.13.0. Feel free to take like a 10x10 array of plain, non-georeferenced values for the tests.

**Comment by mthh** [comment]
Thanks for the data, i took exactly 10x10 values on the problematic area, non-georeferenced, and I modified a bit the values before including them in a test case.
